---
name        : Passing Curiosity
tagline     : Just some stuff
uri         : http://passingcuriosity.com
tagspace    : /tag/
email       : comment@passingcuriosity.com
lang        : en
charset     : UTF-8
destination : public
server_port : 4567
auto        : false
lsi         : false
pygments    : true
permalink   : /:year/:title/
markdown    : rdiscount
exclude     : [public, tmp, README.markdown, config.ru]
