---
name        : Passing Curiosity
tagline     : Just some stuff
uri         : http://passingcuriosity.com
email       : comment@passingcuriosity.com
lang        : en
charset     : UTF-8
destination : _site
server_port : 4567
auto        : false
lsi         : false
pygments    : true
permalink   : /:year/:title/
markdown    : rdiscount
exclude     : [htdocs, jekyll, README.markdown]
